### ISSUE TITLE
SingleInstallBroadcastReceiver security warning in AndroidManifest.xml

### ISSUE THREAD

**Issue by mtsahakis** [AppsFlyerSDK/AppsFlyerAndroidSDK#12]
When I use

```
<receiver
            android:name="com.appsflyer.SingleInstallBroadcastReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
</receiver>
```

I receive a warning in Android Studio "Exported receiver does not require permission"

If we add 

`android:permission="android.permission.INSTALL_PACKAGES"`

The notification goes away. Can you verify if the SDK will then work as expected?

**Comment by afdima** [comment]
Switch to google play referrer library instead of broadcast receiver https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#integration-22-adding-android-install-referrer-to-your-app

**Comment by mtsahakis** [comment]
Thank you for the reply. Still, if we need the receiver for out-of-store attribution, will the SDK work if we add the aforementioned android:permission="android.permission.INSTALL_PACKAGES" permission?

**Comment by afdima** [comment]
<img width="1392" alt="Screenshot 2020-04-29 at 23 54 24" src="https://user-images.githubusercontent.com/60660004/80646136-ddc90680-8a74-11ea-8986-32f1d4f7653e.png">
According to android studio hints, permission is required to limit apps from which you will receive broadcast to those who contain this permission. So if the app or store has this permission you are fine, if not you will not receive this broadcast.
