### ISSUE TITLE
fullBackupContent cause manifest merge to fail

### ISSUE THREAD

**Issue by leonardoxh** [AppsFlyerSDK/AppsFlyerAndroidSDK#3]
Hi, if we upgrade the apps flyer to version 4.10.0 we get a manifest error due the fullBackupContent.

**Comment by af-vs** [comment]
Hi @leonardoxh 

We have added built-in backup rules to the new version of SDK to make sure AppsFlyer data is not transferred between reinstalls or different devices.

If you have your own backup rules specified, please merge them with AppsFlyer rules manually by adding the following rule:

```
<full-backup-content>
    ...//your custom rules
    <exclude domain="sharedpref" path="appsflyer-data"/>
</full-backup-content>
```
Alternatively, if no custom backup rules are specified for your app, you can add `tools:replace="android:fullBackupContent"` to <application> element at AndroidManifest.xml to override default backup setting with those from AppsFlyer SDK.

**Comment by leonardoxh** [comment]
Ok, it did the trick but don't you think this is something that should be in the documentation?

**Comment by af-vs** [comment]
@leonardoxh thanks for the update! We will make sure to add this to our Help Center.
